### ISSUE TITLE
occurrences.get exception in demos documention

### ISSUE THREAD

**Issue by tucotuco** [sckott/pygbif#39]
From

https://github.com/sckott/pygbif/blob/master/demos/pygbif-intro.ipynb

The example
```
from pygbif import occurrences
occurrences.get(key = 252408386)
```
Throws an exception

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pygbif/occurrences/get.py", line 17, in get
    out = gbif_GET(url, {}, **kwargs)
  File "/Library/Python/2.7/site-packages/pygbif/gbifutils.py", line 19, in gbif_GET
    out.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://api.gbif.org/v1/occurrence/252408386
```

**Comment by sckott** [comment]
@tucotuco thanks for the heads up on this - that occurrence key does not exist anymore :( 

I'll update the docs and make sure all egs work ... ⏲

**Comment by tucotuco** [comment]
Thank you!
