### ISSUE TITLE
NameError: name 'identifierTyp' is not defined

### ISSUE THREAD

**Issue by data-biodiversity-aq** [sckott/pygbif#48]
Hello, just wanna report a possible typo in the library:

Version:
Python 3.6.2
pygbif 0.2.0

How to reproduce:

```
from pygbif import registry
registry.installations(data='dataset', uuid='1cbabffe-9073-4007-ba1e-40ebcda6e302')
```

Trackback:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "foo/bar/python3.6/site-packages/pygbif/registry/installations.py", line 41, in installations
    'identifierType': identifierTyp}
NameError: name 'identifierTyp' is not defined
```

Thank you so much.

**Comment by sckott** [comment]
thanks for the report @data-biodiversity-aq 👌 

I'll have a look

**Comment by sckott** [comment]
reinstall from github, should work now
