### ISSUE TITLE
No current publication of pygbif on conda-forge

### ISSUE THREAD

**Issue by pjgoodall** [sckott/pygbif#83]
The current publication of `pygbif` on the conda platform is nearly 5 years old. Can I encourage `pygbif`  to be published on [conda-forge](https://conda-forge.org/#contribute) please? Recently [python-dwca-reader](https://python-dwca-reader.readthedocs.io/en/latest/) was given an automated build onto conda-forge after a 7-year hiatus (many thanks to [Jordan Cook](https://github.com/JWCook)). 

Please see: 

1. https://github.com/conda-forge/python-dwca-reader-feedstock
2. https://github.com/conda-forge/staged-recipes/pull/14969
3. [python-dwca-reader on conda-forge](https://anaconda.org/conda-forge/python-dwca-reader)

**Comment by sckott** [comment]
thanks for the ping @pjgoodall 

I set up a [recipe](https://github.com/sckott/staged-recipes/blob/pygbif/recipes/pygbif/meta.yaml) but it didn't work when I ran it locally. Perhaps I need to include something about requirements.txt in the recipe

<details> <summary><strong>CONFIG=osx64 ./.scripts/run_docker_build.sh</strong></summary>

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 174
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: 5ZSH:XI6P:ITWO:NJ4Q:HJ24:XDL6:EXII:PCPP:V6DI:ARFE:SWTA:42AO
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 42
  Goroutines: 46
  System Time: 2021-06-01T22:46:15.748640314Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

./.scripts/run_docker_build.sh: line 24: shyaml: command not found
WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Falling back to quay.io/condaforge/linux-anvil-comp7
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.
+ export PYTHONUNBUFFERED=1
+ PYTHONUNBUFFERED=1
+ cat
+ cp -r /home/conda/staged-recipes /home/conda/staged-recipes-copy
+ find /home/conda/staged-recipes-copy/recipes -maxdepth 1 -name .DS_Store -delete
+ echo 'Pending recipes.'
Pending recipes.
+ ls -la /home/conda/staged-recipes-copy/recipes
total 32
drwxr-xr-x  8 conda conda 4096 Jun  1 22:46 .
drwxr-xr-x 10 conda conda 4096 Jun  1 22:46 ..
drwxr-xr-x  2 conda conda 4096 Jun  1 22:46 example
drwxr-xr-x  2 conda conda 4096 Jun  1 22:46 fcmaes
drwxr-xr-x  2 conda conda 4096 Jun  1 22:46 koncept
drwxr-xr-x  2 conda conda 4096 Jun  1 22:46 pygbif
drwxr-xr-x  2 conda conda 4096 Jun  1 22:46 r-available
drwxr-xr-x  2 conda conda 4096 Jun  1 22:46 r-freqprof
+ echo 'Finding recipes merged in master and removing them from the build.'
Finding recipes merged in master and removing them from the build.
+ pushd /home/conda/staged-recipes/recipes
+ '[' False == True ']'
+ git ls-tree --name-only master -- .
+ xargs -I '{}' sh -c 'rm -rf ~/staged-recipes-copy/recipes/{} && echo Removing recipe: {}'
Removing recipe: example
Removing recipe: fcmaes
Removing recipe: koncept
Removing recipe: r-available
Removing recipe: r-freqprof
+ popd
+ conda index /home/conda/staged-recipes/build_artifacts
+ conda install --yes --quiet 'conda>4.7.12' 'conda-forge-ci-setup=3.*' conda-forge-pinning networkx=2.4 'conda-build>=3.16'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - conda-build[version='>=3.16']
    - conda-forge-ci-setup=3
    - conda-forge-pinning
    - conda[version='>4.7.12']
    - networkx=2.4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.5.30  |       ha878542_0         136 KB  conda-forge
    certifi-2021.5.30          |   py38h578d9bd_0         141 KB  conda-forge
    click-8.0.1                |   py38h578d9bd_0         146 KB  conda-forge
    conda-env-2.6.0            |                1           2 KB  conda-forge
    conda-forge-ci-setup-3.9.4 |   py38hcd7a344_0          36 KB  conda-forge
    conda-forge-pinning-2021.06.01.05.21.06|       hd8ed1ab_0          16 KB  conda-forge
    decorator-5.0.9            |     pyhd8ed1ab_0          11 KB  conda-forge
    jq-1.6                     |    h36c2ea0_1000         346 KB  conda-forge
    networkx-2.4               |             py_1         1.2 MB  conda-forge
    oniguruma-6.9.7.1          |       h7f98852_0         409 KB  conda-forge
    shyaml-0.6.2               |     pyhd3deb0d_0          21 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.4 MB

The following NEW packages will be INSTALLED:

  click              conda-forge/linux-64::click-8.0.1-py38h578d9bd_0
  conda-env          conda-forge/noarch::conda-env-2.6.0-1
  conda-forge-ci-se~ conda-forge/linux-64::conda-forge-ci-setup-3.9.4-py38hcd7a344_0
  conda-forge-pinni~ conda-forge/noarch::conda-forge-pinning-2021.06.01.05.21.06-hd8ed1ab_0
  decorator          conda-forge/noarch::decorator-5.0.9-pyhd8ed1ab_0
  jq                 conda-forge/linux-64::jq-1.6-h36c2ea0_1000
  networkx           conda-forge/noarch::networkx-2.4-py_1
  oniguruma          conda-forge/linux-64::oniguruma-6.9.7.1-h7f98852_0
  shyaml             conda-forge/noarch::shyaml-0.6.2-pyhd3deb0d_0

The following packages will be UPDATED:

  ca-certificates                      2020.12.5-ha878542_0 --> 2021.5.30-ha878542_0
  certifi                          2020.12.5-py38h578d9bd_1 --> 2021.5.30-py38h578d9bd_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ export FEEDSTOCK_ROOT=/home/conda/staged-recipes
+ FEEDSTOCK_ROOT=/home/conda/staged-recipes
+ export CI_SUPPORT=/home/conda/staged-recipes-copy/.ci_support
+ CI_SUPPORT=/home/conda/staged-recipes-copy/.ci_support
+ setup_conda_rc /home/conda/staged-recipes /home/conda/staged-recipes-copy/recipes /home/conda/staged-recipes-copy/.ci_support/osx64.yaml
Warning: 'conda-forge' already in 'channels' list, moving to the top
+ source run_conda_forge_build_setup
++ export PYTHONUNBUFFERED=1
++ PYTHONUNBUFFERED=1
++ conda config --set show_channel_urls true
++ conda config --set auto_update_conda false
++ conda config --set add_pip_as_python_dependency false
++ export CONDA_BLD_PATH=/home/conda/staged-recipes/build_artifacts
++ CONDA_BLD_PATH=/home/conda/staged-recipes/build_artifacts
++ set +u
++ '[' '' = drone ']'
++ export CPU_COUNT=2
++ CPU_COUNT=2
+++ cat /home/conda/staged-recipes/conda-forge.yml
+++ shyaml get-value channel_priority strict
++ conda config --set channel_priority strict
++ [[ ! -z '' ]]
++ '[' '!' -z osx64 ']'
++ '[' '!' -z '' ']'
++ cat /home/conda/staged-recipes-copy/.ci_support/osx64.yaml
c_compiler:
  - clang
cxx_compiler:
  - clangxx
fortran_compiler:
  - gfortran
channel_sources:
  - conda-forge,defaults
target_platform:
  - osx-64
++ set -u
++ mkdir -p /opt/conda/etc/conda/activate.d
++ echo 'export CONDA_BLD_PATH='\''/home/conda/staged-recipes/build_artifacts'\'''
++ '[' -n 2 ']'
++ echo 'export CPU_COUNT='\''2'\'''
++ echo 'export PYTHONUNBUFFERED='\''1'\'''
+++ cat /home/conda/staged-recipes-copy/.ci_support/osx64.yaml
+++ shyaml get-value cuda_compiler_version.0 None
++ CUDA_VERSION=None
++ [[ None != \N\o\n\e ]]
++++ dirname /opt/conda/bin/run_conda_forge_build_setup
+++ cd /opt/conda/bin
+++ pwd
++ SCRIPT_DIR=/opt/conda/bin
++ source /opt/conda/bin/cross_compile_support.sh
++++ jq -r .platform
++++ conda info --json
+++ BUILD_PLATFORM=linux-64
+++ '[' -f /home/conda/staged-recipes-copy/.ci_support/osx64.yaml ']'
++++ cat /home/conda/staged-recipes-copy/.ci_support/osx64.yaml
++++ shyaml get-value target_platform.0 linux-64
+++ HOST_PLATFORM=osx-64
+++ HOST_PLATFORM=osx-64
+++ [[ osx-64 != \l\i\n\u\x\-\6\4 ]]
+++ echo 'export CONDA_BUILD_CROSS_COMPILATION=1'
+++ export CONDA_BUILD_CROSS_COMPILATION=1
+++ CONDA_BUILD_CROSS_COMPILATION=1
+++ '[' -f /home/conda/staged-recipes-copy/.ci_support/osx64.yaml ']'
+++ echo build_platform:
+++ echo '- linux-64'
+++ [[ linux-64 == \l\i\n\u\x\-\6\4 ]]
+++ [[ osx-64 == linux-* ]]
++ '[' -f /home/conda/staged-recipes-copy/.ci_support/osx64.yaml ']'
+++ shyaml get-value MACOSX_DEPLOYMENT_TARGET.0 0
+++ cat /home/conda/staged-recipes-copy/.ci_support/osx64.yaml
++ need_osx_sdk=0
++ [[ 0 != \0 ]]
++ conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.10.final.0
       virtual packages : __linux=5.10.25=0
                          __glibc=2.12=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.10 Linux/5.10.25-linuxkit centos/6.10 glibc/2.12
                UID:GID : 501:501
             netrc file : None
           offline mode : False

++ conda config --show-sources
==> /home/conda/.condarc <==
add_pip_as_python_dependency: False
auto_update_conda: False
channel_priority: strict
channels:
  - conda-forge
  - defaults
show_channel_urls: True
conda-build:
  root-dir: /home/conda/staged-recipes/build_artifacts

==> envvars <==
bld_path: /home/conda/staged-recipes/build_artifacts

++ conda list --show-channel-urls
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
anaconda-client           1.7.2              pyhd8ed1ab_1    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
cffi                      1.14.5           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
click                     8.0.1            py38h578d9bd_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
conda                     4.10.1           py38h578d9bd_0    conda-forge
conda-build               3.21.4           py38h578d9bd_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-forge-ci-setup      3.9.4            py38hcd7a344_0    conda-forge
conda-forge-pinning       2021.06.01.05.21.06      hd8ed1ab_0    conda-forge
conda-package-handling    1.7.3            py38h497a2fe_0    conda-forge
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
curl                      7.76.1               hea6ffbf_2    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
expat                     2.3.0                h9c3ff4c_0    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
git                       2.30.2          pl5320h24fefe6_1    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        4.0.1            py38h578d9bd_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    3.0.0              pyhd8ed1ab_0    conda-forge
jq                        1.6               h36c2ea0_1000    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libarchive                3.5.1                h3f442fb_1    conda-forge
libcurl                   7.76.1               h2574ce0_2    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblief                   0.10.1               he1b5a44_2    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.0.0            py38h497a2fe_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.4                        py_1    conda-forge
oniguruma                 6.9.7.1              h7f98852_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
patch                     2.7.6             h7f98852_1002    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.32.0               h36c2ea0_0    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.7.0              pyhd8ed1ab_0    conda-forge
psutil                    5.8.0            py38h497a2fe_1    conda-forge
py-lief                   0.10.1           py38h348cfbe_2    conda-forge
pycosat                   0.6.3           py38h497a2fe_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.10          h49503c6_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-libarchive-c       2.9              py38h578d9bd_2    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ripgrep                   12.1.1               h516909a_1    conda-forge
ruamel_yaml               0.15.80         py38h497a2fe_1004    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
shyaml                    0.6.2              pyhd3deb0d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
su-exec                   0.2               h516909a_1002    conda-forge
tini                      0.18.0            h14c3975_1001    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
+ find /home/conda/staged-recipes-copy/recipes -mindepth 2 -maxdepth 2 -type f -name yum_requirements.txt
+ xargs -r /usr/bin/sudo -n yum install -y
+ grep -v -e '^#' -e '^$'
+ xargs -n1 cat
+ test 1 == 1
+ python /home/conda/staged-recipes-copy/.ci_support/build_all.py
Building pygbif with conda-forge/label/main
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING conda_build.config:arch(318): Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
rendering /home/conda/staged-recipes-copy/recipes/pygbif for linux-64
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING conda_build.config:platform(332): Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Computed that there are 1 distributions to build from 1 recipes
Resolved dependencies, will be built in the following order:
    pygbif-0.5.0-on-linux-64
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING conda_build.metadata:ns_cfg(118): No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO conda_build.variants:_combine_spec_dictionaries(234): Adding in variants from internal_defaults
Adding in variants from /opt/conda/conda_build_config.yaml
INFO conda_build.variants:_combine_spec_dictionaries(234): Adding in variants from /opt/conda/conda_build_config.yaml
Adding in variants from /home/conda/staged-recipes-copy/.ci_support/linux64.yaml
INFO conda_build.variants:_combine_spec_dictionaries(234): Adding in variants from /home/conda/staged-recipes-copy/.ci_support/linux64.yaml
Attempting to finalize metadata for pygbif
INFO conda_build.metadata:finalize_outputs_pass(748): Attempting to finalize metadata for pygbif
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['pygbif-0.5.0-pyh6c4a22f_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/conda/staged-recipes/build_artifacts/pygbif_1622587822896/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-conda_forge          conda-forge
    _openmp_mutex:    4.5-1_gnu                conda-forge
    ca-certificates:  2021.5.30-ha878542_0     conda-forge
    certifi:          2021.5.30-py39hf3d152e_0 conda-forge
    ld_impl_linux-64: 2.35.1-hea4e1c9_2        conda-forge
    libffi:           3.3-h58526e2_2           conda-forge
    libgcc-ng:        9.3.0-h2828fa1_19        conda-forge
    libgomp:          9.3.0-h2828fa1_19        conda-forge
    libstdcxx-ng:     9.3.0-h6de172a_19        conda-forge
    ncurses:          6.2-h58526e2_4           conda-forge
    openssl:          1.1.1k-h7f98852_0        conda-forge
    pip:              21.1.2-pyhd8ed1ab_0      conda-forge
    python:           3.9.4-hffdb5ce_0_cpython conda-forge
    python_abi:       3.9-1_cp39               conda-forge
    readline:         8.1-h46c0cb4_0           conda-forge
    setuptools:       49.6.0-py39hf3d152e_3    conda-forge
    sqlite:           3.35.5-h74cdb3f_0        conda-forge
    tk:               8.6.10-h21135ba_1        conda-forge
    tzdata:           2021a-he74cb21_0         conda-forge
    wheel:            0.36.2-pyhd3deb0d_0      conda-forge
    xz:               5.2.5-h516909a_1         conda-forge
    zlib:             1.2.11-h516909a_1010     conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Source cache directory is: /home/conda/staged-recipes/build_artifacts/src_cache
INFO conda_build.source:download_to_cache(44): Source cache directory is: /home/conda/staged-recipes/build_artifacts/src_cache
Downloading source to cache: pygbif-0.5.0_342988e96f.tar.gz
INFO conda_build.source:download_to_cache(69): Downloading source to cache: pygbif-0.5.0_342988e96f.tar.gz
Downloading https://pypi.io/packages/source/p/pygbif/pygbif-0.5.0.tar.gz
INFO conda_build.source:download_to_cache(83): Downloading https://pypi.io/packages/source/p/pygbif/pygbif-0.5.0.tar.gz
Success
INFO conda_build.source:download_to_cache(94): Success
Extracting download
source tree in: /home/conda/staged-recipes/build_artifacts/pygbif_1622587822896/work
export PREFIX=/home/conda/staged-recipes/build_artifacts/pygbif_1622587822896/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export BUILD_PREFIX=/home/conda/staged-recipes/build_artifacts/pygbif_1622587822896/_build_env
export SRC_DIR=/home/conda/staged-recipes/build_artifacts/pygbif_1622587822896/work
Using pip 21.1.2 from $PREFIX/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-w46zhc41
Created temporary directory: /tmp/pip-req-tracker-6c0x8lcn
Initialized build tracking at /tmp/pip-req-tracker-6c0x8lcn
Created build tracker: /tmp/pip-req-tracker-6c0x8lcn
Entered build tracker: /tmp/pip-req-tracker-6c0x8lcn
Created temporary directory: /tmp/pip-install-8wa295w3
Processing $SRC_DIR
  Created temporary directory: /tmp/pip-req-build-jmpg1lev
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-6c0x8lcn'
    Running setup.py (path:/tmp/pip-req-build-jmpg1lev/setup.py) egg_info for package from file://$SRC_DIR
    Created temporary directory: /tmp/pip-pip-egg-info-l8js60ig
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-jmpg1lev/setup.py", line 5, in <module>
        from pygbif import package_metadata
      File "/tmp/pip-req-build-jmpg1lev/pygbif/__init__.py", line 38, in <module>
        from .occurrences import search, get, count, download
      File "/tmp/pip-req-build-jmpg1lev/pygbif/occurrences/__init__.py", line 21, in <module>
        from .search import search
      File "/tmp/pip-req-build-jmpg1lev/pygbif/occurrences/search.py", line 3, in <module>
        from pygbif.gbifutils import gbif_baseurl, bool2str, requests_argset, gbif_GET
      File "/tmp/pip-req-build-jmpg1lev/pygbif/gbifutils.py", line 1, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
WARNING: Discarding file:///home/conda/staged-recipes/build_artifacts/pygbif_1622587822896/work. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    r = self.factory.make_requirement_from_install_req(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 444, in make_requirement_from_install_req
    raise self._build_failures[ireq.link]
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    super().__init__(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 36, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 538, in _generate_metadata
    return generate_metadata_legacy(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 67, in generate_metadata
    call_subprocess(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file://$SRC_DIR from build tracker '/tmp/pip-req-tracker-6c0x8lcn'
Removed build tracker: '/tmp/pip-req-tracker-6c0x8lcn'
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 175, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 100, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 156, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2191, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/staged-recipes/build_artifacts/pygbif_1622587822896/work/conda_build.sh']' returned non-zero exit status 1.
```

</details>

**Comment by JWCook** [comment]
Looks like you just need to add the requirements from your `setup.py` to
`requirements.run`:
```yaml
requirements:
    host:
        - python
        - pip
    run:
        - requests >=2.7
        - etc.
```

**Comment by pjgoodall** [comment]
Thanks @JWCook will put this on my list. I need to learn how to do this anyway.

**Comment by JWCook** [comment]
If/when you submit PRs for those, feel free to ping me if you run into any problems.

**Comment by sckott** [comment]
> looks like geojson_rewind and geomet don't have conda packages available, so those would need to be published first.

Thanks, so I should wait for this, correct?

**Comment by JWCook** [comment]
Right, there's nothing else to do until those dependencies are published.

**Comment by sckott** [comment]
thanks. ran again after [adding deps to the meta file](https://github.com/sckott/pygbif/issues/83#issuecomment-852582532) - and ran into the missing `geojson_rewind` - so will wait for that

**Comment by Rassine** [comment]
> thanks. ran again after [adding deps to the meta file](https://github.com/sckott/pygbif/issues/83#issuecomment-852582532) - and ran into the missing `geojson_rewind` - so will wait for that

If I'm not mistaken,  `geojson_rewind` exist now as a conda package under the name `geojson-rewind` [here](https://anaconda.org/conda-forge/geojson-rewind), Are you still planning on building `pygbif` on conda ? 

I would be happy to help but I'm still learning to do conda recepe on tools that needs `pygbif`

**Comment by sckott** [comment]
i no longer maintain this. @CecSve ?

**Comment by CecSve** [comment]
Thank you - we will look into it!
